name: Update Wiki Index

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # 毎日深夜に実行

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Wiki
        uses: actions/checkout@v3
        with:
          repository: 'j-komatsu/myCheatSheet.wiki'
          path: 'wiki'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies (if any)  # ✅ インデントを修正
        run: |
          if [ -s requirements.txt ]; then 
            pip install -r requirements.txt
          else 
            echo "No dependencies to install"
          fi

      - name: Generate Index
        run: python wiki/generate_index.py wiki

      - name: Commit and Push Changes
        env:
          MYAUTOWIKITOKEN: ${{ secrets.MYAUTOWIKITOKEN }}
        run: |
          cd wiki
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${MYAUTOWIKITOKEN}@github.com/j-komatsu/myCheatSheet.wiki.git
          git add INDEX.md
          git commit -m "Update Wiki Inde x"
          git push origin HEAD
